#############################################################################
# Makefile for building: PyrLK-QMLTracker
# Generated by qmake (3.1) (Qt 5.13.0)
# Project:  PyrLK-QMLTracker.pro
# Template: app
# Command: /Users/Abel/Qt5.13.0/5.13.0/clang_64/bin/qmake -o Makefile PyrLK-QMLTracker.pro -spec macx-clang CONFIG+=x86_64 CONFIG+=qtquickcompiler
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_QUICK_LIB -DQT_MULTIMEDIA_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.12 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -O2 -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.12 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I/usr/local/Cellar/opencv3/3.1.0_4/include -I/usr/local/Cellar/opencv3/3.1.0_4/include/opencv -I/Users/Abel/Qt5.13.0/5.13.0/clang_64/lib/QtQuick.framework/Headers -I/Users/Abel/Qt5.13.0/5.13.0/clang_64/lib/QtMultimedia.framework/Headers -I/Users/Abel/Qt5.13.0/5.13.0/clang_64/lib/QtGui.framework/Headers -I/Users/Abel/Qt5.13.0/5.13.0/clang_64/lib/QtQml.framework/Headers -I/Users/Abel/Qt5.13.0/5.13.0/clang_64/lib/QtNetwork.framework/Headers -I/Users/Abel/Qt5.13.0/5.13.0/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/AGL.framework/Headers -I/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/macx-clang -F/Users/Abel/Qt5.13.0/5.13.0/clang_64/lib
QMAKE         = /Users/Abel/Qt5.13.0/5.13.0/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /Users/Abel/Qt5.13.0/5.13.0/clang_64/bin/qmake -install qinstall
QINSTALL_PROGRAM = /Users/Abel/Qt5.13.0/5.13.0/clang_64/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = PyrLK-QMLTracker1.0.0
DISTDIR = /Users/Abel/Shared/2016_4/1_Game/workspace/tracking/PyrLK-QMLTracker/.tmp/PyrLK-QMLTracker1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -stdlib=libc++ -headerpad_max_install_names $(EXPORT_ARCH_ARGS) -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.12 -Wl,-rpath,@executable_path/../Frameworks -Wl,-rpath,/Users/Abel/Qt5.13.0/5.13.0/clang_64/lib
LIBS          = $(SUBLIBS) -F/Users/Abel/Qt5.13.0/5.13.0/clang_64/lib -L/usr/local/lib -L/usr/local/Cellar/opencv3/3.1.0_4/share/OpenCV/3rdparty/lib -L/usr/local/Cellar/opencv3/3.1.0_4/lib -lopencv_stitching -lopencv_superres -lopencv_videostab -lopencv_aruco -lopencv_bgsegm -lopencv_bioinspired -lopencv_ccalib -lopencv_dnn -lopencv_dpm -lopencv_fuzzy -lopencv_line_descriptor -lopencv_optflow -lopencv_plot -lopencv_reg -lopencv_saliency -lopencv_stereo -lopencv_structured_light -lopencv_rgbd -lopencv_surface_matching -lopencv_tracking -lopencv_datasets -lopencv_text -lopencv_face -lopencv_xfeatures2d -lopencv_shape -lopencv_video -lopencv_ximgproc -lopencv_calib3d -lopencv_features2d -lopencv_flann -lopencv_xobjdetect -lopencv_objdetect -lopencv_ml -lopencv_xphoto -lippicv -lopencv_highgui -lopencv_videoio -lopencv_imgcodecs -lopencv_photo -lopencv_imgproc -lopencv_core -framework QtQuick -framework QtMultimedia -framework QtGui -framework QtQml -framework QtNetwork -framework QtCore -framework DiskArbitration -framework IOKit -framework OpenGL -framework AGL   
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = filter.cpp \
		main.cpp \
		opencvhelper.cpp main_qml.cpp \
		qmlcache_loader.cpp \
		moc_filter.cpp
OBJECTS       = filter.o \
		main.o \
		opencvhelper.o \
		main_qml.o \
		qmlcache_loader.o \
		moc_filter.o
DIST          = /Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/features/spec_pre.prf \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/qdevice.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/features/device_config.prf \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/common/unix.conf \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/common/mac.conf \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/common/macx.conf \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/common/sanitize.conf \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/common/gcc-base.conf \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/common/gcc-base-mac.conf \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/common/clang.conf \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/common/clang-mac.conf \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/qconfig.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_3danimation.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_bodymovin_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_charts.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_core.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_designer.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_gui.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_help.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_location.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_network.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_networkauth.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_positioningquick.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_qml.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_quick.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_repparser.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_repparser_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_script.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_service_support_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_sql.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_svg.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_webview.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_xml.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/features/qt_functions.prf \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/features/qt_config.prf \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/macx-clang/qmake.conf \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/features/spec_post.prf \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/features/exclusive_builds.prf \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/features/mac/sdk.prf \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/features/toolchain.prf \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/features/mac/toolchain.prf \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/features/default_pre.prf \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/features/mac/default_pre.prf \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/features/resolve_config.prf \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/features/default_post.prf \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/features/mac/default_post.prf \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/features/mac/objective_c.prf \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/features/link_pkgconfig.prf \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/features/resources.prf \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/features/qtquickcompiler.prf \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/features/mac/mac.prf \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/features/warn_on.prf \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/features/qt.prf \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/features/moc.prf \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/features/unix/opengl.prf \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/features/unix/thread.prf \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/features/qmake_use.prf \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/features/file_copies.prf \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/features/mac/rez.prf \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/features/testcase_targets.prf \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/features/exceptions.prf \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/features/yacc.prf \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/features/lex.prf \
		PyrLK-QMLTracker.pro filter.h \
		opencvhelper.h \
		rgbframehelper.h filter.cpp \
		main.cpp \
		opencvhelper.cpp
QMAKE_TARGET  = PyrLK-QMLTracker
DESTDIR       = 
TARGET        = PyrLK-QMLTracker

####### Custom Variables
EXPORT_QMAKE_MAC_SDK = macosx
EXPORT_QMAKE_MAC_SDK_VERSION = 10.13
EXPORT_QMAKE_XCODE_DEVELOPER_PATH = /Applications/Xcode.app/Contents/Developer
EXPORT_VALID_ARCHS = x86_64
EXPORT_ACTIVE_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(ARCHS))
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ACTIVE_ARCHS), $(EXPORT_ACTIVE_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))
EXPORT__PRO_FILE_ = /Users/Abel/Shared/2016_4/1_Game/workspace/tracking/PyrLK-QMLTracker/PyrLK-QMLTracker.pro


include /Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/features/mac/sdk.mk
first: all
####### Build rules

PyrLK-QMLTracker:  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: PyrLK-QMLTracker.pro /Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/macx-clang/qmake.conf /Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/features/spec_pre.prf \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/qdevice.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/features/device_config.prf \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/common/unix.conf \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/common/mac.conf \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/common/macx.conf \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/common/sanitize.conf \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/common/gcc-base.conf \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/common/gcc-base-mac.conf \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/common/clang.conf \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/common/clang-mac.conf \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/qconfig.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_3danimation.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_bodymovin_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_charts.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_core.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_designer.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_gui.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_help.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_location.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_network.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_networkauth.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_positioningquick.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_qml.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_quick.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_repparser.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_repparser_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_script.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_service_support_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_sql.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_svg.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_webview.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_xml.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/features/qt_functions.prf \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/features/qt_config.prf \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/macx-clang/qmake.conf \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/features/spec_post.prf \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/features/exclusive_builds.prf \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/features/mac/sdk.prf \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/features/toolchain.prf \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/features/mac/toolchain.prf \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/features/default_pre.prf \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/features/mac/default_pre.prf \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/features/resolve_config.prf \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/features/default_post.prf \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/features/mac/default_post.prf \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/features/mac/objective_c.prf \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/features/link_pkgconfig.prf \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/features/resources.prf \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/features/qtquickcompiler.prf \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/features/mac/mac.prf \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/features/warn_on.prf \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/features/qt.prf \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/features/moc.prf \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/features/unix/opengl.prf \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/features/unix/thread.prf \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/features/qmake_use.prf \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/features/file_copies.prf \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/features/mac/rez.prf \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/features/testcase_targets.prf \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/features/exceptions.prf \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/features/yacc.prf \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/features/lex.prf \
		PyrLK-QMLTracker.pro \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/lib/QtQuick.framework/QtQuick.prl \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/lib/QtMultimedia.framework/QtMultimedia.prl \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/lib/QtGui.framework/QtGui.prl \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/lib/QtQml.framework/QtQml.prl \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/lib/QtNetwork.framework/QtNetwork.prl \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -o Makefile PyrLK-QMLTracker.pro -spec macx-clang CONFIG+=x86_64 CONFIG+=qtquickcompiler
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/features/spec_pre.prf:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/qdevice.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/features/device_config.prf:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/common/unix.conf:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/common/mac.conf:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/common/macx.conf:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/common/sanitize.conf:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/common/gcc-base.conf:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/common/gcc-base-mac.conf:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/common/clang.conf:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/common/clang-mac.conf:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/qconfig.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_3danimation.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_3dextras.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_3drender.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_3drender_private.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_bodymovin_private.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_charts.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_charts_private.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_core.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_core_private.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_datavisualization.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_dbus.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_designer.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_gamepad.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_gui.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_help.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_help_private.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_location.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_location_private.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_macextras.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_network.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_network_private.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_networkauth.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_nfc.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_opengl.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_positioning.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_positioningquick.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_positioningquick_private.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_purchasing.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_qml.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_quick.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_quickshapes_private.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_quicktemplates2.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_repparser.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_repparser_private.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_script.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_script_private.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_scxml.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_scxml_private.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_sensors.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_serialbus.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_serialport.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_service_support_private.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_sql.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_svg.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_testlib.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_texttospeech.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_uitools.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_virtualkeyboard.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_webengine.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_webengine_private.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_webenginecore.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_websockets.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_webview.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_widgets.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_xml.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/features/qt_functions.prf:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/features/qt_config.prf:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/macx-clang/qmake.conf:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/features/spec_post.prf:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/features/exclusive_builds.prf:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/features/mac/sdk.prf:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/features/toolchain.prf:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/features/mac/toolchain.prf:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/features/default_pre.prf:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/features/mac/default_pre.prf:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/features/resolve_config.prf:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/features/default_post.prf:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/features/mac/default_post.prf:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/features/mac/objective_c.prf:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/features/link_pkgconfig.prf:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/features/resources.prf:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/features/qtquickcompiler.prf:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/features/mac/mac.prf:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/features/warn_on.prf:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/features/qt.prf:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/features/moc.prf:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/features/unix/opengl.prf:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/features/unix/thread.prf:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/features/qmake_use.prf:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/features/file_copies.prf:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/features/mac/rez.prf:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/features/mac/asset_catalogs.prf:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/features/testcase_targets.prf:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/features/exceptions.prf:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/features/yacc.prf:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/features/lex.prf:
PyrLK-QMLTracker.pro:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/lib/QtQuick.framework/QtQuick.prl:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/lib/QtMultimedia.framework/QtMultimedia.prl:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/lib/QtGui.framework/QtGui.prl:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/lib/QtQml.framework/QtQml.prl:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/lib/QtNetwork.framework/QtNetwork.prl:
/Users/Abel/Qt5.13.0/5.13.0/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile PyrLK-QMLTracker.pro -spec macx-clang CONFIG+=x86_64 CONFIG+=qtquickcompiler

qmake_all: FORCE


all: Makefile PyrLK-QMLTracker

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents main.qml $(DISTDIR)/
	$(COPY_FILE) --parents qml.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents filter.h opencvhelper.h rgbframehelper.h $(DISTDIR)/
	$(COPY_FILE) --parents filter.cpp main.cpp opencvhelper.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

xcodeproj:
	@$(QMAKE) -spec macx-xcode $(EXPORT__PRO_FILE_)

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_qmlcache_make_all: main_qml.cpp
compiler_qmlcache_clean:
	-$(DEL_FILE) main_qml.cpp
main_qml.cpp: main.qml \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/bin/qmlcachegen
	/Users/Abel/Qt5.13.0/5.13.0/clang_64/bin/qmlcachegen --resource=/Users/Abel/Shared/2016_4/1_Game/workspace/tracking/PyrLK-QMLTracker/qml.qrc -o main_qml.cpp main.qml

compiler_qmlcache_loader_make_all: qmlcache_loader.cpp
compiler_qmlcache_loader_clean:
	-$(DEL_FILE) qmlcache_loader.cpp
qmlcache_loader.cpp: qml.qrc /Users/Abel/Qt5.13.0/5.13.0/clang_64/bin/qmlcachegen
	/Users/Abel/Qt5.13.0/5.13.0/clang_64/bin/qmlcachegen --resource-file-mapping=/Users/Abel/Shared/2016_4/1_Game/workspace/tracking/PyrLK-QMLTracker/qml.qrc -o qmlcache_loader.cpp qml.qrc

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/features/data/dummy.cpp
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -pipe -stdlib=libc++ -O2 -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.12 -Wall -W -dM -E -o moc_predefs.h /Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_filter.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_filter.cpp
moc_filter.cpp: filter.h \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/lib/QtMultimedia.framework/Headers/QAbstractVideoFilter \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/lib/QtMultimedia.framework/Headers/qabstractvideofilter.h \
		/usr/local/Cellar/opencv3/3.1.0_4/include/opencv2/core/core.hpp \
		/usr/local/Cellar/opencv3/3.1.0_4/include/opencv2/core.hpp \
		/usr/local/Cellar/opencv3/3.1.0_4/include/opencv2/core/cvdef.h \
		/usr/local/Cellar/opencv3/3.1.0_4/include/opencv2/core/hal/interface.h \
		/usr/local/Cellar/opencv3/3.1.0_4/include/opencv2/core/version.hpp \
		/usr/local/Cellar/opencv3/3.1.0_4/include/opencv2/core/base.hpp \
		/usr/local/Cellar/opencv3/3.1.0_4/include/opencv2/core/cvstd.hpp \
		/usr/local/Cellar/opencv3/3.1.0_4/include/opencv2/core/ptr.inl.hpp \
		/usr/local/Cellar/opencv3/3.1.0_4/include/opencv2/core/neon_utils.hpp \
		/usr/local/Cellar/opencv3/3.1.0_4/include/opencv2/core/traits.hpp \
		/usr/local/Cellar/opencv3/3.1.0_4/include/opencv2/core/matx.hpp \
		/usr/local/Cellar/opencv3/3.1.0_4/include/opencv2/core/saturate.hpp \
		/usr/local/Cellar/opencv3/3.1.0_4/include/opencv2/core/fast_math.hpp \
		/usr/local/Cellar/opencv3/3.1.0_4/include/opencv2/core/types.hpp \
		/usr/local/Cellar/opencv3/3.1.0_4/include/opencv2/core/mat.hpp \
		/usr/local/Cellar/opencv3/3.1.0_4/include/opencv2/core/bufferpool.hpp \
		/usr/local/Cellar/opencv3/3.1.0_4/include/opencv2/core/mat.inl.hpp \
		/usr/local/Cellar/opencv3/3.1.0_4/include/opencv2/core/persistence.hpp \
		/usr/local/Cellar/opencv3/3.1.0_4/include/opencv2/core/operations.hpp \
		/usr/local/Cellar/opencv3/3.1.0_4/include/opencv2/core/cvstd.inl.hpp \
		/usr/local/Cellar/opencv3/3.1.0_4/include/opencv2/core/utility.hpp \
		/usr/local/Cellar/opencv3/3.1.0_4/include/opencv2/core/core_c.h \
		/usr/local/Cellar/opencv3/3.1.0_4/include/opencv2/core/types_c.h \
		/usr/local/Cellar/opencv3/3.1.0_4/include/opencv2/core/optim.hpp \
		/usr/local/Cellar/opencv3/3.1.0_4/include/opencv2/video/tracking.hpp \
		/usr/local/Cellar/opencv3/3.1.0_4/include/opencv2/imgproc.hpp \
		/usr/local/Cellar/opencv3/3.1.0_4/include/opencv2/imgproc/imgproc_c.h \
		/usr/local/Cellar/opencv3/3.1.0_4/include/opencv2/imgproc/types_c.h \
		/usr/local/Cellar/opencv3/3.1.0_4/include/opencv2/objdetect/objdetect.hpp \
		/usr/local/Cellar/opencv3/3.1.0_4/include/opencv2/objdetect.hpp \
		/usr/local/Cellar/opencv3/3.1.0_4/include/opencv2/objdetect/detection_based_tracker.hpp \
		/usr/local/Cellar/opencv3/3.1.0_4/include/opencv2/objdetect/objdetect_c.h \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/lib/QtGui.framework/Headers/QCursor \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/lib/QtGui.framework/Headers/qcursor.h \
		moc_predefs.h \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/bin/moc
	/Users/Abel/Qt5.13.0/5.13.0/clang_64/bin/moc $(DEFINES) --include /Users/Abel/Shared/2016_4/1_Game/workspace/tracking/PyrLK-QMLTracker/moc_predefs.h -I/Users/Abel/Qt5.13.0/5.13.0/clang_64/mkspecs/macx-clang -I/Users/Abel/Shared/2016_4/1_Game/workspace/tracking/PyrLK-QMLTracker -I/usr/local/Cellar/opencv3/3.1.0_4/include -I/usr/local/Cellar/opencv3/3.1.0_4/include/opencv -I/Users/Abel/Qt5.13.0/5.13.0/clang_64/lib/QtQuick.framework/Headers -I/Users/Abel/Qt5.13.0/5.13.0/clang_64/lib/QtMultimedia.framework/Headers -I/Users/Abel/Qt5.13.0/5.13.0/clang_64/lib/QtGui.framework/Headers -I/Users/Abel/Qt5.13.0/5.13.0/clang_64/lib/QtQml.framework/Headers -I/Users/Abel/Qt5.13.0/5.13.0/clang_64/lib/QtNetwork.framework/Headers -I/Users/Abel/Qt5.13.0/5.13.0/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.0.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include -F/Users/Abel/Qt5.13.0/5.13.0/clang_64/lib filter.h -o moc_filter.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_qmlcache_clean compiler_qmlcache_loader_clean compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

filter.o: filter.cpp filter.h \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/lib/QtMultimedia.framework/Headers/QAbstractVideoFilter \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/lib/QtMultimedia.framework/Headers/qabstractvideofilter.h \
		/usr/local/Cellar/opencv3/3.1.0_4/include/opencv2/core/core.hpp \
		/usr/local/Cellar/opencv3/3.1.0_4/include/opencv2/core.hpp \
		/usr/local/Cellar/opencv3/3.1.0_4/include/opencv2/core/cvdef.h \
		/usr/local/Cellar/opencv3/3.1.0_4/include/opencv2/core/hal/interface.h \
		/usr/local/Cellar/opencv3/3.1.0_4/include/opencv2/core/version.hpp \
		/usr/local/Cellar/opencv3/3.1.0_4/include/opencv2/core/base.hpp \
		/usr/local/Cellar/opencv3/3.1.0_4/include/opencv2/core/cvstd.hpp \
		/usr/local/Cellar/opencv3/3.1.0_4/include/opencv2/core/ptr.inl.hpp \
		/usr/local/Cellar/opencv3/3.1.0_4/include/opencv2/core/neon_utils.hpp \
		/usr/local/Cellar/opencv3/3.1.0_4/include/opencv2/core/traits.hpp \
		/usr/local/Cellar/opencv3/3.1.0_4/include/opencv2/core/matx.hpp \
		/usr/local/Cellar/opencv3/3.1.0_4/include/opencv2/core/saturate.hpp \
		/usr/local/Cellar/opencv3/3.1.0_4/include/opencv2/core/fast_math.hpp \
		/usr/local/Cellar/opencv3/3.1.0_4/include/opencv2/core/types.hpp \
		/usr/local/Cellar/opencv3/3.1.0_4/include/opencv2/core/mat.hpp \
		/usr/local/Cellar/opencv3/3.1.0_4/include/opencv2/core/bufferpool.hpp \
		/usr/local/Cellar/opencv3/3.1.0_4/include/opencv2/core/mat.inl.hpp \
		/usr/local/Cellar/opencv3/3.1.0_4/include/opencv2/core/persistence.hpp \
		/usr/local/Cellar/opencv3/3.1.0_4/include/opencv2/core/operations.hpp \
		/usr/local/Cellar/opencv3/3.1.0_4/include/opencv2/core/cvstd.inl.hpp \
		/usr/local/Cellar/opencv3/3.1.0_4/include/opencv2/core/utility.hpp \
		/usr/local/Cellar/opencv3/3.1.0_4/include/opencv2/core/core_c.h \
		/usr/local/Cellar/opencv3/3.1.0_4/include/opencv2/core/types_c.h \
		/usr/local/Cellar/opencv3/3.1.0_4/include/opencv2/core/optim.hpp \
		/usr/local/Cellar/opencv3/3.1.0_4/include/opencv2/video/tracking.hpp \
		/usr/local/Cellar/opencv3/3.1.0_4/include/opencv2/imgproc.hpp \
		/usr/local/Cellar/opencv3/3.1.0_4/include/opencv2/imgproc/imgproc_c.h \
		/usr/local/Cellar/opencv3/3.1.0_4/include/opencv2/imgproc/types_c.h \
		/usr/local/Cellar/opencv3/3.1.0_4/include/opencv2/objdetect/objdetect.hpp \
		/usr/local/Cellar/opencv3/3.1.0_4/include/opencv2/objdetect.hpp \
		/usr/local/Cellar/opencv3/3.1.0_4/include/opencv2/objdetect/detection_based_tracker.hpp \
		/usr/local/Cellar/opencv3/3.1.0_4/include/opencv2/objdetect/objdetect_c.h \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/lib/QtGui.framework/Headers/QCursor \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/lib/QtGui.framework/Headers/qcursor.h \
		opencvhelper.h \
		/usr/local/Cellar/opencv3/3.1.0_4/include/opencv2/imgproc/imgproc.hpp \
		rgbframehelper.h \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/lib/QtGui.framework/Headers/QImage \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/lib/QtGui.framework/Headers/qimage.h \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/lib/QtMultimedia.framework/Headers/QAbstractVideoBuffer \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/lib/QtMultimedia.framework/Headers/qabstractvideobuffer.h \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/lib/QtGui.framework/Headers/QOpenGLContext \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/lib/QtGui.framework/Headers/qopenglcontext.h \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/lib/QtGui.framework/Headers/QOpenGLFunctions \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/lib/QtGui.framework/Headers/qopenglfunctions.h \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/lib/QtGui.framework/Headers/QOpenGLFramebufferObject \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/lib/QtGui.framework/Headers/qopenglframebufferobject.h \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/lib/QtCore.framework/Headers/QFile \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/lib/QtCore.framework/Headers/qfile.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o filter.o filter.cpp

main.o: main.cpp /Users/Abel/Qt5.13.0/5.13.0/clang_64/lib/QtGui.framework/Headers/QGuiApplication \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/lib/QtGui.framework/Headers/qguiapplication.h \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/lib/QtQml.framework/Headers/QQmlApplicationEngine \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/lib/QtQml.framework/Headers/qqmlapplicationengine.h \
		filter.h \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/lib/QtMultimedia.framework/Headers/QAbstractVideoFilter \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/lib/QtMultimedia.framework/Headers/qabstractvideofilter.h \
		/usr/local/Cellar/opencv3/3.1.0_4/include/opencv2/core/core.hpp \
		/usr/local/Cellar/opencv3/3.1.0_4/include/opencv2/core.hpp \
		/usr/local/Cellar/opencv3/3.1.0_4/include/opencv2/core/cvdef.h \
		/usr/local/Cellar/opencv3/3.1.0_4/include/opencv2/core/hal/interface.h \
		/usr/local/Cellar/opencv3/3.1.0_4/include/opencv2/core/version.hpp \
		/usr/local/Cellar/opencv3/3.1.0_4/include/opencv2/core/base.hpp \
		/usr/local/Cellar/opencv3/3.1.0_4/include/opencv2/core/cvstd.hpp \
		/usr/local/Cellar/opencv3/3.1.0_4/include/opencv2/core/ptr.inl.hpp \
		/usr/local/Cellar/opencv3/3.1.0_4/include/opencv2/core/neon_utils.hpp \
		/usr/local/Cellar/opencv3/3.1.0_4/include/opencv2/core/traits.hpp \
		/usr/local/Cellar/opencv3/3.1.0_4/include/opencv2/core/matx.hpp \
		/usr/local/Cellar/opencv3/3.1.0_4/include/opencv2/core/saturate.hpp \
		/usr/local/Cellar/opencv3/3.1.0_4/include/opencv2/core/fast_math.hpp \
		/usr/local/Cellar/opencv3/3.1.0_4/include/opencv2/core/types.hpp \
		/usr/local/Cellar/opencv3/3.1.0_4/include/opencv2/core/mat.hpp \
		/usr/local/Cellar/opencv3/3.1.0_4/include/opencv2/core/bufferpool.hpp \
		/usr/local/Cellar/opencv3/3.1.0_4/include/opencv2/core/mat.inl.hpp \
		/usr/local/Cellar/opencv3/3.1.0_4/include/opencv2/core/persistence.hpp \
		/usr/local/Cellar/opencv3/3.1.0_4/include/opencv2/core/operations.hpp \
		/usr/local/Cellar/opencv3/3.1.0_4/include/opencv2/core/cvstd.inl.hpp \
		/usr/local/Cellar/opencv3/3.1.0_4/include/opencv2/core/utility.hpp \
		/usr/local/Cellar/opencv3/3.1.0_4/include/opencv2/core/core_c.h \
		/usr/local/Cellar/opencv3/3.1.0_4/include/opencv2/core/types_c.h \
		/usr/local/Cellar/opencv3/3.1.0_4/include/opencv2/core/optim.hpp \
		/usr/local/Cellar/opencv3/3.1.0_4/include/opencv2/video/tracking.hpp \
		/usr/local/Cellar/opencv3/3.1.0_4/include/opencv2/imgproc.hpp \
		/usr/local/Cellar/opencv3/3.1.0_4/include/opencv2/imgproc/imgproc_c.h \
		/usr/local/Cellar/opencv3/3.1.0_4/include/opencv2/imgproc/types_c.h \
		/usr/local/Cellar/opencv3/3.1.0_4/include/opencv2/objdetect/objdetect.hpp \
		/usr/local/Cellar/opencv3/3.1.0_4/include/opencv2/objdetect.hpp \
		/usr/local/Cellar/opencv3/3.1.0_4/include/opencv2/objdetect/detection_based_tracker.hpp \
		/usr/local/Cellar/opencv3/3.1.0_4/include/opencv2/objdetect/objdetect_c.h \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/lib/QtGui.framework/Headers/QCursor \
		/Users/Abel/Qt5.13.0/5.13.0/clang_64/lib/QtGui.framework/Headers/qcursor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

opencvhelper.o: opencvhelper.cpp opencvhelper.h \
		/usr/local/Cellar/opencv3/3.1.0_4/include/opencv2/imgproc/imgproc.hpp \
		/usr/local/Cellar/opencv3/3.1.0_4/include/opencv2/imgproc.hpp \
		/usr/local/Cellar/opencv3/3.1.0_4/include/opencv2/core.hpp \
		/usr/local/Cellar/opencv3/3.1.0_4/include/opencv2/core/cvdef.h \
		/usr/local/Cellar/opencv3/3.1.0_4/include/opencv2/core/hal/interface.h \
		/usr/local/Cellar/opencv3/3.1.0_4/include/opencv2/core/version.hpp \
		/usr/local/Cellar/opencv3/3.1.0_4/include/opencv2/core/base.hpp \
		/usr/local/Cellar/opencv3/3.1.0_4/include/opencv2/core/cvstd.hpp \
		/usr/local/Cellar/opencv3/3.1.0_4/include/opencv2/core/ptr.inl.hpp \
		/usr/local/Cellar/opencv3/3.1.0_4/include/opencv2/core/neon_utils.hpp \
		/usr/local/Cellar/opencv3/3.1.0_4/include/opencv2/core/traits.hpp \
		/usr/local/Cellar/opencv3/3.1.0_4/include/opencv2/core/matx.hpp \
		/usr/local/Cellar/opencv3/3.1.0_4/include/opencv2/core/saturate.hpp \
		/usr/local/Cellar/opencv3/3.1.0_4/include/opencv2/core/fast_math.hpp \
		/usr/local/Cellar/opencv3/3.1.0_4/include/opencv2/core/types.hpp \
		/usr/local/Cellar/opencv3/3.1.0_4/include/opencv2/core/mat.hpp \
		/usr/local/Cellar/opencv3/3.1.0_4/include/opencv2/core/bufferpool.hpp \
		/usr/local/Cellar/opencv3/3.1.0_4/include/opencv2/core/mat.inl.hpp \
		/usr/local/Cellar/opencv3/3.1.0_4/include/opencv2/core/persistence.hpp \
		/usr/local/Cellar/opencv3/3.1.0_4/include/opencv2/core/operations.hpp \
		/usr/local/Cellar/opencv3/3.1.0_4/include/opencv2/core/cvstd.inl.hpp \
		/usr/local/Cellar/opencv3/3.1.0_4/include/opencv2/core/utility.hpp \
		/usr/local/Cellar/opencv3/3.1.0_4/include/opencv2/core/core_c.h \
		/usr/local/Cellar/opencv3/3.1.0_4/include/opencv2/core/types_c.h \
		/usr/local/Cellar/opencv3/3.1.0_4/include/opencv2/core/optim.hpp \
		/usr/local/Cellar/opencv3/3.1.0_4/include/opencv2/imgproc/imgproc_c.h \
		/usr/local/Cellar/opencv3/3.1.0_4/include/opencv2/imgproc/types_c.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o opencvhelper.o opencvhelper.cpp

main_qml.o: main_qml.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main_qml.o main_qml.cpp

qmlcache_loader.o: qmlcache_loader.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qmlcache_loader.o qmlcache_loader.cpp

moc_filter.o: moc_filter.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_filter.o moc_filter.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/PyrLK-QMLTracker/bin || mkdir -p $(INSTALL_ROOT)/opt/PyrLK-QMLTracker/bin
	-$(QINSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/opt/PyrLK-QMLTracker/bin/$(QMAKE_TARGET)
	-$(STRIP) $(INSTALL_ROOT)/opt/PyrLK-QMLTracker/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/opt/PyrLK-QMLTracker/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/PyrLK-QMLTracker/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

